### ISSUE TITLE
Error: no step configured

### ISSUE THREAD

**Issue by rossrollin** [TeliaSoneraNorge/divx-concourse-tasks#55]
Guys am I missing something here? Following your readme I get the following error:

fly -t concourse-poc sp -p terraform-pipeline -c pipeline.yml -v aws-access-key=redacted -v aws-secret-key=redacted
error: error unmarshaling JSON: while decoding JSON: no step configured
______________________________________________________________________________

pipeline.yml:

```
---
resources:
  - name: master-branch
    type: git
    source:
      uri: https://github.com/rossrollin/terraform-poc
      branch: master
  - name: common-tasks
    type: git
    source:
      uri: https://github.com/telia-oss/concourse-tasks.git
      branch: master

jobs:
  - name: terraform-pipeline
    serial: true
    plan:
      - aggregate:
        - get: master-branch
          trigger: true
        - get: common-tasks
          params: { submodules: [ terraform ] }
        - task: terraform-plan
          file: common-tasks/terraform/0.12.29.yml
          input_mapping: { source: master-branch }
          params:
            command: plan
            cache: true
            access_key: ((aws-access-key))
            secret_key: ((aws-secret-key))
            directory: terraform-poc/dev
```

Very new to concourse though so could be doing something wrong, I just cant figure out what
